modifed jenkins file six commit

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -54,20 +54,21 @@ pipeline{
                 
             }
         }
-        post{
-            always{
-                echo "Cleaning up workspace"
-                cleanWs()
+    }
+    post{
+        always{
+            sh 'docker logout || true'
+            sh 'docker image prune -f || true'
+            echo "Cleaning up workspace"
+            cleanWs()
             }
-            success{
-                echo "Build and push successful"
+        success{
+            echo "Build and Docker push completed successfully."
             }
             failure{
-                echo "Build or push failed"
+            echo "Build or push failed"
             }
         }
 
 
     }
-
-}
